### PR TITLE
add max_cpu

### PR DESCRIPTION
**Pull request by matthewberry**
These changes add a max_cpu parameter to match GP.

I ran `make run_all_methods` with this version and confirmed all output files were identical to those produced by knowengdev/feature_prioritization_pipeline:02_20_2018, which is the version currently used in production and which predates all max_cpu changes.

Note that running `make run_all_methods` in this version does result in warnings, much like we saw with the new GP:

```
python3 ../src/feature_prioritization.py -run_directory ./run_dir -run_file TEST_4_FP_many_drugs_t_test.yml
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/usr/local/lib/python3.4/dist-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
```

Again, I assume that because the outputs are identical to those produced in the production image, the underlying issue wasn't introduced by my changes; it's just that the updated versions of pandas and/or numpy are more verbose.  

Also note that `make unit_tests` fails in both this new version and in the reference version:

```
root@35cbc1b6e799:/home/test# make unit_test_setup
mkdir -p ./unit/tmp
root@35cbc1b6e799:/home/test# make unit_tests
cd unit; make all_unit_tests
make[1]: Entering directory `/home/test/unit'
PYTHONPATH='../../src/' python3 -m unittest discover --pattern=test_*.py
.F.
======================================================================
FAIL: test_get_t_test_correlation (test_get_t_test_correlation.TestGet_t_test_correlation)
check t_test against hand calculated value, and check that return values are real numbers
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/test/unit/test_get_t_test_correlation.py", line 44, in test_get_t_test_correlation
    self.assertTrue(np.isfinite(corr_arr[k]), msg='t_test Correlation Array is Not Finite')
AssertionError: False is not true : t_test Correlation Array is Not Finite

----------------------------------------------------------------------
Ran 3 tests in 0.007s

FAILED (failures=1)
make[1]: *** [all_unit_tests] Error 1
make[1]: Leaving directory `/home/test/unit'
make: *** [unit_tests] Error 2
```

As another FYI, `make env_setup` fails in the reference version and in this one, apparently because there are no gzipped inputs:

```
root@35cbc1b6e799:/home/test# make env_setup
mkdir -p ./run_dir/results 
cp ../data/run_files/*.yml ./run_dir 
Decompress input data...
gzip -d 
gzip: compressed data not read from a terminal. Use -f to force decompression.
For help, type: gzip -h
make: *** [decompress_input_data] Error 1
```

### CODE REVIEW

**Comment by matthewberry** [comment]
Output of `make verification_tests`:

```
root@7ee30fb0a6ac:/home/test# make verification_tests
python3 ./integration/verify_benchmarks.py
make[1]: Entering directory `/home/test'
mkdir -p ./run_dir/results 
cp ../data/run_files/*.yml ./run_dir 
Decompress input data...
gzip -d 
gzip: compressed data not read from a terminal. Use -f to force decompression.
For help, type: gzip -h
make[1]: *** [decompress_input_data] Error 1
make[1]: Leaving directory `/home/test'
../data/verification/zPhenotype_Expander/phenotype_expander_result.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/L-685458_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Erlotinib_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/AEW541_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/TKI258_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/PD-0325901_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Nilotinib_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/AZD6244_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Lapatinib_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Topotecan_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/TAE684_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Nutlin-3_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Irinotecan_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/PF2341066_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Sorafenib_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/PLX4720_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/PHA-665752_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/17-AAG_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/AZD0530_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/ZD-6474_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/RAF265_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Panobinostat_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/Paclitaxel_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/PD-0332991_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_4_FP_bootstrap_t_test/LBW242_bootstrap_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Nutlin-3_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/L-685458_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Panobinostat_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Lapatinib_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/ZD-6474_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/TAE684_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/LBW242_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/PD-0325901_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Paclitaxel_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Erlotinib_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/17-AAG_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/RAF265_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Irinotecan_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/PLX4720_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/TKI258_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/PD-0332991_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/AZD0530_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/AZD6244_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/PHA-665752_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Sorafenib_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Topotecan_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/AEW541_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/PF2341066_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_1_FP_pearson/Nilotinib_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/PLX4720_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/17-AAG_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/ZD-6474_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/AZD6244_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/PD-0325901_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Irinotecan_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Nilotinib_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/L-685458_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/PD-0332991_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Paclitaxel_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Panobinostat_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Sorafenib_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Topotecan_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Nutlin-3_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/PF2341066_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Erlotinib_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/AEW541_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/AZD0530_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/LBW242_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/Lapatinib_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/RAF265_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/TAE684_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/PHA-665752_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_3_FP_t_test/TKI258_correlation_t_test.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/L-685458_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/AEW541_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/TAE684_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Panobinostat_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Nutlin-3_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Paclitaxel_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/LBW242_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/PF2341066_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Irinotecan_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/AZD6244_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/PLX4720_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/PD-0325901_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/RAF265_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Erlotinib_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/AZD0530_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/PD-0332991_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Sorafenib_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/ZD-6474_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/TKI258_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Nilotinib_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Topotecan_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/17-AAG_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/PHA-665752_bootstrap_correlation_pearson.tsv PASS
../data/verification/BENCHMARK_2_FP_bootstrap_pearson/Lapatinib_bootstrap_correlation_pearson.tsv PASS
```

**Comment by dlanier** [comment]
It is nice that they are passing.
Note that the text file I attached to the last email showed the ones that fail on my system with the pre-merge version.


I haven’t had time to detail the code but
“commit d78c459703f92312955c69b62cffee62a12a5a5b”
looks like array_of_jobs might not be right.

Have a meeting this morning – will look more closely at it later.

Dan

PS
I think the bug was initiated when knpackage got a fix for the pandas “future warning” about a variable is being set on a copy of a slice.
The fix needed the future version of pandas which needed a future version of numpy and none of us in this future had a server and time to test it all on. (I’m speculating but would look there first).

**Comment by matthewberry** [comment]
> I think the bug was initiated when knpackage got a fix for the pandas “future warning” about a variable is being set on a copy of a slice.

Hi @dlanier. Which bug are you referring to--the RuntimeWarnings from numpy? To be clear, I'm not attempting to fix them here; I'm merely trying to add a max_cpu parameter without affecting the outputs. But if they do signal a genuine bug, I believe it'd predate this PR and in fact have been in production since at least February, so we'd want to get that fixed ASAP.

**Comment by matthewberry** [comment]
> Note that the text file I attached to the last email showed the ones that fail on my system with the pre-merge version.

@dlanier it looks to me like the file you sent contains GP output, not FP output. Or am I missing something? Or does some of this discussion belong on the GP pull request instead?

**Comment by candicegjing** [comment]
Looks good to me!

**Pull request merged**
